MAX_ITERATIONS = 10
IMPROVEMENT_THRESHOLD = 0.02
MIN_ATTACKER_CONFIDENCE = 0.6
MIN_BUILDER_CONFIDENCE = 0.5
STALL_ITERATIONS = 2
VALIDATION_DEPTH = 5
VALIDATION_POSITIONS = 30
ENGINE_TIMEOUT_S = 10.0
